library(imputeTS)
Coxsbazer=tidal[ ,c(1,7)]

data=ts(Coxsbazer, start=c(1977,01), frequency=12)
data=na.interpolation(data,option = "spline")
cycle(data)
jan=as.data.frame(subset(data, cycle(data) == 1))
a=mean(jan$Coxsbazer)
View(a)
jan=as.data.frame(subset(data, cycle(data) == 2))
b=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 3))
c=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 4))
d=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 5))
e=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 6))
f=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 7))
g=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 8))
h=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 9))
i=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 10))
j=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 11))
k=mean(jan$Coxsbazer)
jan=as.data.frame(subset(data, cycle(data) == 12))
l=mean(jan$Coxsbazer)
myMonth=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")
months=as.data.frame(myMonth)

Coxsbazer=rbind(a,b,c,d,e,f,g,h,i,j,k,l)
mong=as.numeric(Coxsbazer)
View(mong)
final_data=cbind(months,mong)
final_data

